use std::env;
use std::fs;
use std::path::Path;

use chacha20poly1305::{
    ChaCha20Poly1305, Key, Nonce,
    aead::{Aead, KeyInit, OsRng},
};
use rand::RngCore;

fn main() {
    println!("cargo:rerun-if-changed=.env");

    let dotenv_path = Path::new(".env");
    if dotenv_path.exists() {
        dotenvy::from_path(dotenv_path).ok();
    }

    // Collect all secrets from .env
    let secrets: &[(&str, &str)] = &[
        ("LASTFM_API_KEY", "LASTFM_API_KEY"),
        ("LASTFM_API_SECRET", "LASTFM_API_SECRET"),
    ];

    let secret_values: Vec<(&str, String)> = secrets
        .iter()
        .map(|(name, var)| {
            let val = env::var(var).unwrap_or_else(|_| {
                panic!(
                    "{var} not set. Create a .env file with the required credentials.\n\
                     Required: LASTFM_API_KEY, LASTFM_API_SECRET"
                )
            });
            (*name, val)
        })
        .collect();

    let mut master_key = [0u8; 32];
    OsRng.fill_bytes(&mut master_key);

    let key_parts: [[u8; 8]; 4] = [
        master_key[0..8].try_into().unwrap(),
        master_key[8..16].try_into().unwrap(),
        master_key[16..24].try_into().unwrap(),
        master_key[24..32].try_into().unwrap(),
    ];

    let masks: [[u8; 8]; 4] = [
        [0x7A, 0x3C, 0x91, 0xE4, 0x5D, 0x2F, 0xB8, 0x6E],
        [0x1F, 0xD4, 0x6B, 0xA2, 0x3E, 0xC7, 0x09, 0x5B],
        [0x8C, 0x0E, 0xF3, 0x27, 0xD1, 0x6A, 0xB5, 0x4F],
        [0xE2, 0x59, 0x3B, 0x76, 0x0D, 0xA8, 0xC4, 0x1E],
    ];

    // Mask each part
    let masked_parts: [[u8; 8]; 4] = key_parts
        .iter()
        .zip(masks.iter())
        .map(|(part, mask)| {
            let mut masked = [0u8; 8];
            for i in 0..8 {
                masked[i] = part[i] ^ mask[i];
            }
            masked
        })
        .collect::<Vec<_>>()
        .try_into()
        .unwrap();

    let cipher = ChaCha20Poly1305::new(Key::from_slice(&master_key));

    let encrypted_secrets: Vec<([u8; 12], Vec<u8>)> = secret_values
        .iter()
        .map(|(_, val)| {
            let mut nonce_bytes = [0u8; 12];
            OsRng.fill_bytes(&mut nonce_bytes);
            let nonce = Nonce::from_slice(&nonce_bytes);
            let ciphertext = cipher
                .encrypt(nonce, val.as_bytes())
                .expect("encryption failed");
            (nonce_bytes, ciphertext)
        })
        .collect();

    let key_part_fns = (0..4)
        .map(|i| {
            let masked = masked_parts[i];
            let mask = masks[i];
            format!(
                r#"#[inline(never)]
#[allow(clippy::identity_op)]
fn key_part_{i}() -> [u8; 8] {{
    [
        0x{:02x} ^ 0x{:02x}, 0x{:02x} ^ 0x{:02x},
        0x{:02x} ^ 0x{:02x}, 0x{:02x} ^ 0x{:02x},
        0x{:02x} ^ 0x{:02x}, 0x{:02x} ^ 0x{:02x},
        0x{:02x} ^ 0x{:02x}, 0x{:02x} ^ 0x{:02x},
    ]
}}"#,
                masked[0],
                mask[0],
                masked[1],
                mask[1],
                masked[2],
                mask[2],
                masked[3],
                mask[3],
                masked[4],
                mask[4],
                masked[5],
                mask[5],
                masked[6],
                mask[6],
                masked[7],
                mask[7],
            )
        })
        .collect::<Vec<_>>()
        .join("\n\n");

    // Generate secret constants
    let secret_consts = encrypted_secrets
        .iter()
        .map(|(nonce, ct)| {
            let nonce_arr: Vec<String> = nonce.iter().map(|b| format!("0x{:02x}", b)).collect();
            let ct_arr: Vec<String> = ct.iter().map(|b| format!("0x{:02x}", b)).collect();
            format!(
                r#"    (&[{}], &[{}]),"#,
                nonce_arr.join(", "),
                ct_arr.join(", "),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    // Generate index constants
    let index_consts = secrets
        .iter()
        .enumerate()
        .map(|(i, (name, _))| format!(r#"pub const {}: usize = {};"#, name, i))
        .collect::<Vec<_>>()
        .join("\n");

    let secret_count = encrypted_secrets.len();

    let generated_code = format!(
        r#"// Auto-generated by build.rs - DO NOT EDIT

use chacha20poly1305::{{
    aead::{{Aead, KeyInit}},
    ChaCha20Poly1305, Key, Nonce,
}};
use std::ptr::write_volatile;

{index_consts}

{key_part_fns}

#[inline(never)]
fn get_master_key() -> [u8; 32] {{
    let mut key = [0u8; 32];
    let p0 = key_part_0();
    let p1 = key_part_1();
    let p2 = key_part_2();
    let p3 = key_part_3();
    key[0..8].copy_from_slice(&p0);
    key[8..16].copy_from_slice(&p1);
    key[16..24].copy_from_slice(&p2);
    key[24..32].copy_from_slice(&p3);
    key
}}

fn zeroize(data: &mut [u8]) {{
    for b in data.iter_mut() {{
        unsafe {{ write_volatile(b, 0) }};
    }}
    std::sync::atomic::fence(std::sync::atomic::Ordering::SeqCst);
}}

const ENCRYPTED_SECRETS: &[(&[u8; 12], &[u8])] = &[
{secret_consts}
];

#[inline(never)]
pub fn reveal_secret(idx: usize) -> String {{
    assert!(idx < {secret_count}, "secret index out of bounds");

    let mut key_bytes = get_master_key();
    let key = Key::from_slice(&key_bytes);
    let cipher = ChaCha20Poly1305::new(key);

    let (nonce_bytes, ciphertext) = ENCRYPTED_SECRETS[idx];
    let nonce = Nonce::from_slice(nonce_bytes);

    let plaintext = cipher
        .decrypt(nonce, ciphertext.as_ref())
        .expect("decryption failed");

    zeroize(&mut key_bytes);

    String::from_utf8(plaintext).expect("invalid utf-8 in secret")
}}
"#,
        index_consts = index_consts,
        key_part_fns = key_part_fns,
        secret_consts = secret_consts,
        secret_count = secret_count,
    );

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("secrets.rs");
    fs::write(&dest_path, generated_code).expect("Failed to write generated secrets");

    // Embed icon in Windows .exe
    #[cfg(target_os = "windows")]
    {
        let rc_path = Path::new("assets/isi-music.rc");
        let icon_path = Path::new("assets/isi-music.ico");
        if rc_path.exists() && icon_path.exists() {
            if let Err(e) = embed_resource::compile("assets/isi-music", embed_resource::NONE)
                .manifest_required()
            {
                println!("cargo:warning=Failed to embed icon: {e:?}");
            }
            println!("cargo:rerun-if-changed=assets/isi-music.rc");
            println!("cargo:rerun-if-changed=assets/isi-music.ico");
        }
    }
}
