#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Action {
    PlayPause,
    NextTrack,
    PrevTrack,
    VolumeUp,
    VolumeDown,
    SeekForward,
    SeekBackward,
    SeekMiddle,
    ToggleShuffle,
    CycleRepeat,
    ToggleRadio,
    GetRecommendations,
    LikeTrack,
    AddToQueue,
    RemoveFromQueue,
    SortTracks,
    NavUp,
    NavDown,
    NavFirst,
    NavLast,
    NavMiddle,
    TabNext,
    TabPrev,
    Enter,
    Back,
    Search,
    QuickSearch,
    Help,
    ToggleCompact,
    ToggleFullscreen,
    ToggleVisualizer,
    ToggleLyrics,
    ToggleDebug,
    ScrollUp,
    ScrollDown,
    Quit,
    OptionsPanel,
    CopyTrackLink,
    ToggleBreadcrumb,
    AddToPlaylist,
    RemoveFromPlaylist,
    DeletePlaylist,
    CommandPrompt,
    FocusLibrary,
    FocusPlaylists,
    FocusTracks,
    FocusQueue,
    JumpToPlaying,
}

impl Action {
    pub(crate) fn all() -> &'static [(&'static str, &'static [&'static str], Action)] {
        use Action::*;
        &[
            ("play_pause", &["space"], PlayPause),
            ("next_track", &["n"], NextTrack),
            ("prev_track", &["p", "P"], PrevTrack),
            ("volume_up", &["="], VolumeUp),
            ("volume_down", &["-"], VolumeDown),
            ("seek_forward", &["right"], SeekForward),
            ("seek_backward", &["left"], SeekBackward),
            ("seek_middle", &["5"], SeekMiddle),
            ("toggle_shuffle", &["s"], ToggleShuffle),
            ("cycle_repeat", &["r"], CycleRepeat),
            ("toggle_radio", &["´"], ToggleRadio),
            ("recommendations", &["alt+r"], GetRecommendations),
            ("like_track", &["l"], LikeTrack),
            ("add_to_queue", &["a"], AddToQueue),
            ("remove_from_queue", &["delete"], RemoveFromQueue),
            ("sort_tracks", &["o"], SortTracks),
            ("nav_up", &["up", "k"], NavUp),
            ("nav_down", &["down", "j"], NavDown),
            ("nav_first", &["ctrl+up"], NavFirst),
            ("nav_last", &["ctrl+down"], NavLast),
            ("nav_middle", &["M"], NavMiddle),
            ("tab_next", &["tab"], TabNext),
            ("tab_prev", &["backtab"], TabPrev),
            ("enter", &["enter"], Enter),
            ("back", &["esc"], Back),
            ("search", &["/"], Search),
            ("quick_search", &["ctrl+f"], QuickSearch),
            ("help", &["?"], Help),
            ("toggle_compact", &["m"], ToggleCompact),
            ("toggle_fullscreen", &["z"], ToggleFullscreen),
            ("toggle_visualizer", &["v"], ToggleVisualizer),
            ("toggle_lyrics", &["y"], ToggleLyrics),
            ("toggle_debug", &["d"], ToggleDebug),
            ("scroll_up", &["pageup"], ScrollUp),
            ("scroll_down", &["pagedown"], ScrollDown),
            ("quit", &["q", "ctrl+c"], Quit),
            ("options_panel", &["t"], OptionsPanel),
            ("copy_track_link", &["ctrl+y"], CopyTrackLink),
            ("toggle_breadcrumb", &["shift+b"], ToggleBreadcrumb),
            ("add_to_playlist", &["A"], AddToPlaylist),
            ("remove_from_playlist", &["D"], RemoveFromPlaylist),
            ("delete_playlist", &["alt+d"], DeletePlaylist),
            ("command_prompt", &[":"], CommandPrompt),
            ("focus_library", &["1"], FocusLibrary),
            ("focus_playlists", &["2"], FocusPlaylists),
            ("focus_tracks", &["3"], FocusTracks),
            ("focus_queue", &["4"], FocusQueue),
            ("jump_to_playing", &["c"], JumpToPlaying),
        ]
    }
}
