pub struct Preset {
    pub name: &'static str,
    pub border_active: &'static str,
    pub border_inactive: &'static str,
    pub highlight_bg: &'static str,
    pub text_primary: &'static str,
    pub text_secondary: &'static str,
    pub accent: &'static str,
    pub background: &'static str,
    pub status_bar: &'static str,
    pub preview: &'static str,
}

pub const PRESETS: &[Preset] = &[
    Preset {
        name: "Neutral Dark",
        border_active: "#d0d0d0",
        border_inactive: "#777777",
        highlight_bg: "#2a2a2a",
        text_primary: "#e6e6e6",
        text_secondary: "#9e9e9e",
        accent: "#c4c4c4",
        background: "#141414",
        status_bar: "#1c1c1c",
        preview: "  ▐\x1b[37m████\x1b[0m▌ neutral dark     ",
    },
    Preset {
        name: "Catppuccin Mocha",
        border_active: "#cba6f7",
        border_inactive: "#585b70",
        highlight_bg: "#313244",
        text_primary: "#cdd6f4",
        text_secondary: "#a6adc8",
        accent: "#89b4fa",
        background: "#1e1e2e",
        status_bar: "#181825",
        preview: "  ▐\x1b[35m████\x1b[0m▌ lavender        ",
    },
    Preset {
        name: "Gruvbox Dark",
        border_active: "#d79921",
        border_inactive: "#504945",
        highlight_bg: "#3c3836",
        text_primary: "#ebdbb2",
        text_secondary: "#a89984",
        accent: "#fe8019",
        background: "#282828",
        status_bar: "#1d2021",
        preview: "  ▐\x1b[33m████\x1b[0m▌ warm amber      ",
    },
    Preset {
        name: "Nord",
        border_active: "#88c0d0",
        border_inactive: "#4c566a",
        highlight_bg: "#3b4252",
        text_primary: "#e5e9f0",
        text_secondary: "#81a1c1",
        accent: "#5e81ac",
        background: "#2e3440",
        status_bar: "#242933",
        preview: "  ▐\x1b[36m████\x1b[0m▌ arctic blue     ",
    },
    Preset {
        name: "Rose Pine",
        border_active: "#eb6f92",
        border_inactive: "#524f67",
        highlight_bg: "#26233a",
        text_primary: "#e0def4",
        text_secondary: "#908caa",
        accent: "#f6c177",
        background: "#191724",
        status_bar: "#1f1d2e",
        preview: "  ▐\x1b[31m████\x1b[0m▌ muted rose      ",
    },
    Preset {
        name: "Tokyo Night",
        border_active: "#7aa2f7",
        border_inactive: "#3b4261",
        highlight_bg: "#1f2335",
        text_primary: "#c0caf5",
        text_secondary: "#9aa5ce",
        accent: "#9ece6a",
        background: "#1a1b26",
        status_bar: "#16161e",
        preview: "  ▐\x1b[34m████\x1b[0m▌ blue / neon     ",
    },
    Preset {
        name: "Dracula",
        border_active: "#bd93f9",
        border_inactive: "#44475a",
        highlight_bg: "#282a36",
        text_primary: "#f8f8f2",
        text_secondary: "#6272a4",
        accent: "#ff79c6",
        background: "#1e1f29",
        status_bar: "#191a21",
        preview: "  ▐\x1b[35m████\x1b[0m▌ purple / pink   ",
    },
    Preset {
        name: "Monochrome",
        border_active: "#ffffff",
        border_inactive: "#666666",
        highlight_bg: "#1a1a1a",
        text_primary: "#cccccc",
        text_secondary: "#888888",
        accent: "#999999",
        background: "#111111",
        status_bar: "#222222",
        preview: "  ▐\x1b[37m████\x1b[0m▌ greyscale       ",
    },
    Preset {
        name: "Clean",
        border_active: "#5c5f77",
        border_inactive: "#3b3d4f",
        highlight_bg: "#1e1e2e",
        text_primary: "#cdd6f4",
        text_secondary: "#6c7086",
        accent: "#89b4fa",
        background: "#11111b",
        status_bar: "#181825",
        preview: "  ▐\x1b[34m░░░░\x1b[0m▌ minimal / clean ",
    },
];
